trigger: none
pool: Ankitpool
stages:
- stage: scanstage
  displayName: scan chal raha hai
  jobs:
  - job: 
    steps:
    # - task: PowerShell@2
    #   displayName: lint (Biome)
    #   inputs:
    #     targetType: 'inline'
    #     script: 'C:\Tools\biome.exe lint $(System.DefaultWorkingDirectory)/'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.11/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)\biome.exe"

           & "$(Agent.ToolsDirectory)\biome.exe" lint "$(System.DefaultWorkingDirectory)"
