trigger:
- main
pool: Ankitpool
stages:
- stage: scanstage
  displayName: scan chal raha hai
  jobs:
  - job: 
    continueOnError: true
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.11/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)\biome.exe"

           & "$(Agent.ToolsDirectory)\biome.exe" lint "$(System.DefaultWorkingDirectory)"
- stage: buildstage
  jobs:
  - job: buildjob
    steps:
    - task: NodeAndNpmTool@1
      inputs:
        versionSpec: '18.x'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          npm install
          npm run build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/build'
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: ContinueDeploy
  jobs:
  - job: 
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.DefaultWorkingDirectory)/build_artifact'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'vm_connection'
        sourceFolder: '$(System.DefaultWorkingDirectory)/build_artifact'
        contents: '**'
        targetFolder: '/home/rferhari'
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'vm_connection'
        runOptions: 'commands'
        commands: 'sudo cp -r /home/rferhari/* /var/www/html'
        readyTimeout: '20000'